<a href="https://colab.research.google.com/github/lbenameur09/Agentic-AI-BUS4-118S/blob/dev/ex1_prompt_chaining.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Exercise 1: Prompt Chaining for Customer Support AI

Tools used: ChatGPT (web) + Google Colab (for documentation/output)

Step 1 Prompt (System + User)

System:
You are a customer support triage assistant. Return ONLY valid JSON. No extra text.

User:
Classify this customer message into JSON with keys:
category (billing/login/shipping/bug/cancellation/other),
sentiment (calm/frustrated/angry),
urgency (low/medium/high),
needs_human (true/false),
confidence (0-1),
rationale (max 12 words).

Customer message:
"I was charged twice for order #7891 and nobody is replying. Fix this ASAP."

In [1]:
step1_output = """{
"category": "billing",
"sentiment": "angry",
"urgency": "high",
"needs_human": true,
"confidence": 0.96,
"rationale": "Double charge and demands immediate resolution."
}"""

print(step1_output)

{
"category": "billing",
"sentiment": "angry",
"urgency": "high",
"needs_human": true,
"confidence": 0.96,
"rationale": "Double charge and demands immediate resolution."
}


Step 2 Prompt

System:
You are a helpful customer support agent. Ask only necessary questions.

User:
Here is the triage JSON: {
"category": "billing",
"sentiment": "angry",
"urgency": "high",
"needs_human": true,
"confidence": 0.96,
"rationale": "Double charge and demands immediate resolution."
}
Write 2-4 questions to gather missing info needed to solve the issue.
Output format:
MissingInfoQuestions: [ ... ]

In [2]:
step2_output = """MissingInfoQuestions: [
"Can you confirm the date and amounts of the two charges you’re seeing?",
"What payment method was used for order #7891?",
"Do both charges appear as completed transactions, or is one still pending?"
]"""
print(step2_output)

MissingInfoQuestions: [
"Can you confirm the date and amounts of the two charges you’re seeing?",
"What payment method was used for order #7891?",
"Do both charges appear as completed transactions, or is one still pending?"
]


Step 3 Prompt

System:
You are a customer support agent. Keep it under 10 lines. Don’t invent policies.

User:
Triage result: {
"category": "billing",
"sentiment": "angry",
"urgency": "high",
"needs_human": true,
"confidence": 0.96,
"rationale": "Double charge and demands immediate resolution."
}
Customer answers:

order_id: 7891

email: customer@example.com

payment_method: Visa ending 4455

amounts: $65 charged twice

Provide:

1 sentence empathy

Numbered solution steps

Fallback option

In [3]:
step3_output = """I’m really sorry this happened — I understand how frustrating double charges are.

I’m escalating this immediately to our billing team with your order ID (7891), Visa ending 4455, and the two $65 charges.

We will verify whether one charge is a duplicate or a pending authorization.

If confirmed as a duplicate, we will initiate a refund to your Visa card.

You’ll receive an email confirmation once the review is complete.

If you don’t see an update within 24 hours, please reply here and we’ll prioritize a live billing specialist to review it directly."""
print(step3_output)

I’m really sorry this happened — I understand how frustrating double charges are.

I’m escalating this immediately to our billing team with your order ID (7891), Visa ending 4455, and the two $65 charges.

We will verify whether one charge is a duplicate or a pending authorization.

If confirmed as a duplicate, we will initiate a refund to your Visa card.

You’ll receive an email confirmation once the review is complete.

If you don’t see an update within 24 hours, please reply here and we’ll prioritize a live billing specialist to review it directly.


Step 4 Prompt

System:
You decide whether to escalate to a human agent. Return ONLY JSON.

User:
Given:
Triage: {
"category": "billing",
"sentiment": "angry",
"urgency": "high",
"needs_human": true,
"confidence": 0.96,
"rationale": "Double charge and demands immediate resolution."
}
Proposed solution: I’m really sorry this happened — I understand how frustrating double charges are.

I’m escalating this immediately to our billing team with your order ID (7891), Visa ending 4455, and the two $65 charges.

We will verify whether one charge is a duplicate or a pending authorization.

If confirmed as a duplicate, we will initiate a refund to your Visa card.

You’ll receive an email confirmation once the review is complete.

If you don’t see an update within 24 hours, please reply here and we’ll prioritize a live billing specialist to review it directly.
Return JSON with:
escalate (true/false),
priority (P1/P2/P3),
reason (max 15 words).

Rules:

Escalate if needs_human=true or urgency=high.

In [4]:
step4_output = """{
"escalate": true,
"priority": "P1",
"reason": "High urgency billing issue requiring human review."
}"""
print(step4_output)

{
"escalate": true,
"priority": "P1",
"reason": "High urgency billing issue requiring human review."
}


Iteration (Before → After)

Before prompt issue: The model returned extra text or messy JSON.
Fix: Added “Return ONLY valid JSON” + strict keys + short rationale constraint.

Include the “before” prompt and “after” prompt (copy them here).

Done.